"""add soft deletes and audit logs

Revision ID: 4ee28b2b3d36
Revises: d9b7b30b9e42
Create Date: 2026-08-20 16:25:54.627598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee28b2b3d36'
down_revision: Union[str, Sequence[str], None] = 'd9b7b30b9e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('workspaces', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('workspaces', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'deleted_at')
    op.drop_column('workspaces', 'is_deleted')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
