"""add otp verification and all tables

Revision ID: d9b7b30b9e42
Revises: a3839a69cbea
Create Date: 2026-08-19 15:16:35.561739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b7b30b9e42'
down_revision: Union[str, Sequence[str], None] = 'a3839a69cbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('verification_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'verification_otp')
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
