"""soft and audit log

Revision ID: dd386988deed
Revises: 4ee28b2b3d36
Create Date: 2026-08-20 19:43:20.552476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd386988deed'
down_revision: Union[str, Sequence[str], None] = '4ee28b2b3d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('comments', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'deleted_at')
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
